import Navigation from '@/components/Navigation'
export default function QuestionsPage() {
  const questions = [
    "What did you make this week?",
    "Are you addicted to cheap dopamine?",
    "What are you thinking about these days?",
    "What are you confused about?",
    "Are you doing what's expected of you, or what you truly want?",
    "What do you want?",
    "How to prepare for the times of change?",
    "Can you be more specific?",
    "What happens to your consciousness when you walk into a teleporter?",
    "What level of resolution would be required to replicate your brain in a way that produces someone you'd still consider 'you'?",
    "What are the key questions?",
    "Why not take a pen and a piece of paper, go offline for 1 hour and resolve one of them?",
    "What does a good future look like?",
    "What's the best argument *against* your current life choices?",
    "What will *not* be said in your eulogy that you wish would be?",
    "What inspires you?",
    "What's a skill you've been *meaning* to learn for years? Why haven't you?",
    "What's an opinion you hold that you've never actually questioned?",
    "Why did the US founding fathers decide that the president must be at least 35 years old?",
    "When was the last time you were truly bored?",
    "Does time exist?",
    "Does the replication crisis in science prove that even experts are trapped in groupthink?",
    "What are you absolutely certain about?",
    "What's something you *think* you want but would hate if you got it?",
    "Which problems in your life are real, and which are invented?",
    "How will history judge your work?",
    "Why will you fail?",
    "What do you know about yourself that others consistently underestimate?",
    "Which views do you claim to hold—though you know they're wrong—just to avoid criticism from your employer or industry?",
    "Why is it easier to do something for the other person than to do the exact same thing for yourself?",
    "What are you flinching from?",
    "Why not just stare at it for 10 minutes?",
    "What's a pain you'd happily endure (forever)?",
    "If you were arrested for being *too* consistent, would there be enough evidence to convict you?",
    "Who benefits most from you staying the same person you are today?",
    "What is AI alignment?",
    "Is your desire for more money based on the false belief that it will solve personal problems that have nothing to do with money?",
    "Why did the empire of Amir Timur (Tamerlane), which expanded from India to Anatolia, collapse within decades after his death, while smaller states like the Bukhara Khanate lasted much longer?",
    "How did the cultural flourishing like observatories, madrasas, and architecture in Samarkand coexist with the brutality of Timur's conquests?",
    "Is 'both sides-ism' just lazy contrarianism?",
    "Why did the Silk Road cities lose global significance after the 16th century, even though they had been world centers of trade and culture?",
    "Why did Central Asian elites (khans, emirs, religious leaders) often **resist modernization** when the Russian Empire introduced railroads, new schools, and industry, while some local reformers (\"Jadids\") pushed for change?",
    "Would you rather be forgotten or remembered for something mediocre?",
    "If thinking for yourself is so valuable, why does society punish independent thought?",
    "Looking back, are you any good at anticipating how you would feel and react to risks that actually occurred?",
    "Why do children who grow up without a real authority become spoiled? Do they?",
    "Is the internet making us more conformist by amplifying groupthink rather than dissent?",
    "What's something you believe that would get you fired if you said it at work? How can you know if it is true.",
    "What's the most _dangerous_ idea you've ever seriously considered?",
    "What strong belief do you hold that's most likely to change?",
    "What great company is no one starting?",
    "Why do corporations spend billions on R&D but rarely discover real 'secrets'?",
    "If the most successful people are contrarian (e.g., Thiel, Musk, Jobs), why do schools train students to be obedient?",
    "Which 'crazy genius' you aspire to emulate is actually just crazy?",
    "Why do we call someone 'crazy' when they're early, but a 'visionary' when they're proven right?",
    "Is the obsession with 'data-driven decisions' killing bold, contrarian bets?",
    "What question are you afraid to ask because you suspect you already know the answer?",
    "Which truths are considered 'immoral' to investigate?",
    "How to measure AI alignment?",
    "Which idea would you defend even if it made you unpopular everywhere?",
    "Which of your heroes would disappoint you if you really knew them?",
    "Why did you do something you regret?",
    "If you could see yourself talk, what would you cringe at the most?",
    "Who has the right answers but you ignore because they're not articulate?",
    "What are we ignoring today that will seem shockingly obvious in a year?",
    "What do you think is currently ignored by the media but will be studied by historians?",
    "How many of your principles are cultural fads?",
    "What are you going to regret in a year?",
    "What's slowing you down the most?",
    "What's your destiny?",
    "How can you do better?",
    "Why do some secrets remain hidden for centuries (e.g., hygiene in medicine), while others are discovered simultaneously (e.g., calculus)?",
    "Will AI discover all new knowledge, or will it just reinforce consensus?",
    "How to solve prompt injections?",
    "When was the last time you asked for help?",
    "Did the person actually tell you no or did you just assume they would?",
    "Who do you want to be more like?",
    "Who do you want to be less like?",
    "Who do you envy that is actually less happy than you are?",
    "What would you do if you were alone in the universe?",
    "Why was Einstein celebrated for rejecting Newtonian physics, but modern dissidents are 'canceled'?",
    "What are bad recommendations you hear in your profession or area of expertise?",
    "What are the biggest time-wasters or distractions in your life?",
    "What's the most common piece of advice you find yourself giving to others?",
    "What are you putting off out of fear?",
    "What are the probable outcomes (both good and bad) if you attempt it?",
    "What's the trade-off you're making without realizing it?",
    "What's the worst-case scenario if you pursued your dream? Is it really that bad?",
    "What's a socially acceptable behavior you think is harmful?",
    "What's the biggest difference between what people *think* will make them happy and what actually does?",
    "What's the worst nutrition or fitness advice you've heard?",
    "What's the most impactful journaling prompt you've used?",
    "What's the best way to recover from burnout?",
    "What's something you've stopped doing that's improved your life?",
    "Are you avoiding hard work by doing things that just look productive?",
    "Are you working on a project that has the potential to be 10x or 100x better than alternatives?",
    "Are you thinking from first principles or relying on assumptions?",
    "What's your real motivation for starting a business?",
    "If your business disappeared tomorrow, would anyone care?",
    "What are you pretending not to know?",
    "What would make you say, 'Wow, that was an amazing life'?",
    "Is this a 'Hell Yes!' or a 'No'?",
    "If your startup failed tomorrow, what would be the real reason—not the excuse?",
    "What are you *embarrassingly* early to?",
    "What's the one thing you're avoiding because it feels too ambitious?",
    "If you had to *lose* all your current customers to find better ones, would you?",
    "What would you work on if no one could ever judge you?",
    "What outdated belief are you still clinging to because it was useful in the past?",
    "What's something you *pretend* to understand but actually don't?",
    "If you could *erase* one widely accepted idea from history, what would it be?",
    "What's something everyone is optimizing for that's actually a trap?",
    "What's the most *illegal* but morally acceptable thing you could do in your field?",
    "What would happen if your industry *stopped* pretending?",
    "What's the most painful truth you've been avoiding?",
    "If you had to *reverse* one of your strongest opinions, which would hurt the most?",
    "What's something you've forgotten that used to excite you as a kid?",
    "What's the biggest opportunity you've missed because you were too afraid to act?",
    "If you died today, what would your biggest professional *waste* have been?",
    "What's a technology that _should_ exist by now but doesn't—because society is preventing it?",
    "What's something we're _accidentally_ making worse by trying to improve it?",
    "If you could instantly abolish one law or regulation, which would unlock the most progress?",
    "What's a dying industry that _deserves_ to die faster?",
    "What's something everyone claims to care about—but their actions prove they don't?",
    "What's a belief that's only popular because it's _unfalsifiable_?",
    "What's a taboo that _shouldn't_ be a taboo?",
    "What's a future that's _likely_ but that nobody is preparing for?",
    "What's the most _overrated_ threat to society—and what's the most _underrated_ one?",
    "If you had to bet, what's a current 'crazy' idea that will be mainstream in 20 years?",
    "What's something we'll look back on as _obviously stupid_—but we can't see it yet?",
    "Who has the most influence over society while being the _least_ accountable?",
    "What's a form of censorship that's so subtle, most people don't even notice it?",
    "If technology makes governments _less_ powerful, what fills the void?",
    "What's a group that's _winning_ in society but pretending to be losing?",
    "What's a primal human desire that tech _still_ hasn't fully exploited?",
    "What's something people _say_ they want from tech—but actually don't?",
    "What's a technology that could _reverse_ a major social problem?",
    "What's the most _dehumanizing_ tech trend that nobody talks about?",
    "What's an institution that _should_ be disrupted but is too emotionally sacred to touch?",
    "What's a job that _shouldn't_ be automated—but will be because it's profitable?",
    "What's a technology we _think_ makes us resilient—but actually increases systemic risk?",
    "What's a _single point of failure_ in modern society that's being ignored?",
    "What's something we're _terrified_ of that would actually solve more problems than it creates?",
    "What if 'disinformation' is just information that _works too well_?",
    "What's a fact that's _true but useless_ because nobody can act on it?",
    "What's something Paul Graham is _wrong_ about but won't admit?",
    "What business that looks like a 'monopoly' today will be a dying industry in 20 years?",
    "Who are widely admired people who are actually doing more harm than good?",
    "How would you destroy [Company X] if you were its competitor with unlimited capital?",
    "What's an industry where the _dumbest_ competitor sets the profit margins for everyone else?",
    "What's a socially acceptable form of insanity that nobody questions?",
    "What's something everyone believes that is actually a collective hallucination?",
    "If you had to design a cult to brainwash smart people, what tactics would you use?",
    "What's a decision that feels 'responsible' but is actually irresponsible in the long run?",
    "What's something you've never regretted saying 'no' to?",
    "What's a 'good' habit that can backfire if taken too far?",
    "What's a modern tradition that future generations will view as barbaric?",
    "What's a widely accepted practice in business that is actually unethical?",
    "What's an example of 'progress' that has made life worse?",
    "If you could erase one law from existence, which would do the most good by disappearing?",
    "What's a skill that was extremely valuable 100 years ago that's useless now—and what current skill will be useless in 100 years?",
    "What's something you _think_ you understand but actually don't?",
    "What's a piece of advice that sounds wise but is actually terrible in practice?",
    "What's something that's true that you wish wasn't true?",
    "What's an irreversible mistake most people don't realize they're making until it's too late?",
    "What's a 'fact' that everyone agrees on today that will be proven wrong in 50 years?",
    "Does solution to AI risk exist?",
    "How can we solve AI risk?",
    "How can we measure AI risk?",
    "What makes you do the right thing?",
    "How do we know if a LLM is telling us what it actually thinks?",
    "If you were forced to bet against the consensus, where would you put your money?",
    "What is a problem that you think only applies to other countries/industries/careers that will eventually hit me?",
    "Who are you afraid of?",
    "If truth is what survives scrutiny, why do most people avoid scrutiny?",
    "Which of your principles would you abandon if they stopped earning you praise and recognition?",
    "How much of what you do is internal benchmark (makes you happy) vs. external benchmark (you think it changes what other people think of you)?",
    "When was the last time you prayed?",
    "What are you proud of?",
    "Why did Krishna reveal himself only to Arjuna?",
    "Is the real purpose of NDAs to hide secrets—or to create the illusion of them?",
    "What's the right way to regulate AI?",
    "Do you feel better or worse after spending time with the person you spend most of your time with?",
    "Was Alexander worse than Hitler?",
    "When should one give up?",
    "What's the ground-truth measure?",
    "How to upload brains w/o discontinuity of consciousness?",
    "Why not travel to your favorite city as often as you can?",
    "Whose views do you criticize that you would actually agree with if you lived in their shoes?",
    "Can a machine learning model be truly contrarian? Will scaling help?",
    "Why do we celebrate 'diversity' in gender and race but not in thought?",
    "Which of your current views would you disagree with if you were born in a different country or generation?",
    "Whose approval are you auditioning for?",
    "What does nobody want to say about this industry?",
    "Whose silence do you mistake for agreement?",
    "If you could not compare yourself to anyone else, how would you define a good life?",
    "What do you think is true but is actually just good marketing?",
    "What looks unsustainable but is actually a new trend we haven't accepted yet?",
    "What has been true for decades that will stop working, but will drag along stubborn adherents because it had such a long track record of success?",
    "Who do you think is smart but is actually full of it?",
    "What do you ignore because it's too painful to accept?",
    "Do the fundamental laws of physics exist?",
    "Am I wasting my time writing these questions?",
    "What have you promised to do and not done yet?",
    "Is consciousness continuous?",
    "Is the failure condition clear?",
    "What are you flinching from thinking about?",
    "Why do people sign false confessions?",
    "When was the last time you talked to someone you really admire?",
    "Is solving alignment different from building AGI?",
    "What have you learned about yourself in the last year?",
    "Are AI capabilities more like those of bombs or of computers?",
    "How does the brain generate consciousness?",
    "Have you spent 1 minute today on your biggest goal?",
    "Have you spent 1 hour today on your biggest goal?",
    "Have you spent 10 hours today on your biggest goal?",
    "What's the most common advice you give to people?",
    "Do you follow it yourself?",
    "Does the world need to be saved?",
    "What can you do in the next 60 seconds that will make you feel proud of yourself?",
    "What are the hardest problems you are excited to solve?",
    "What are you wrong about?",
    "What's AGI?",
    "What's a business that should exist but doesn't because of cultural/political taboos?",
    "Why not invite someone you like talking to for a dinner?",
    "Who's consistently ahead of you?",
    "Why don't you catch up?",
    "How to overcome the second law of thermodynamics?",
    "What do you wish you could do but you're absolutely confident you can't?",
    "How do you know?",
    "What's the humanity's frontier?",
    "What exists?",
    "What doesn't exist?",
    "What should exist but doesn't? What do we need that we don't have?",
    "What is the book (or books) you've given most as a gift, and why?",
    "If you were on my deathbed tomorrow, what would you regret most?",
    "Why do we have 'thought leaders' when real progress comes from 'thought heretics'?",
    "When was the last time you closed your eyes for a minute and asked yourself if you're doing the right thing?",
    "Why do secular liberals still preach 'sacred' values (equality, climate, etc.) like a religion?",
    "What can you do all day long and feel great going to bed?",
    "What is the shape of the solution to AI alignment?",
    "Where in the world is your tribe?",
    "Are you thinking independently or going along with the tribal views of a group you want to be associated with?",
    "What's the ETA to the Dyson sphere around the sun?",
    "Why do schools teach students to memorize existing knowledge rather than seek out undiscovered truths?",
    "What are the key factors of pluralist future?",
    "Do you like yourself when you look in the mirror?",
    "What's the strongest case for technological accelerationism?",
    "What's the strongest case against technological accelerationism?",
    "Does anyone believe they're evil?",
    "What do other people tell you about you that you are always surprised to hear?",
    "Why?",
    "Which future memory are you creating right now, and will you be proud to own it?",
    "What's a 'fact' everyone in your industry accepts that might be wrong?",
    "Why does anything exist at all?",
    "Do you believe in yourself more than you believed 5 years ago?",
    "What would you do if you couldn't make the world better?",
    "How do the experiences of sleep, general anesthesia, and death differ?",
    "Have you read a good history book?",
    "What are you trying to do?",
    "How did humanity manage to never deploy a hydrogen bomb?",
    "What are the key factors of a good future?",
    "What do you have no competitors in?",
    "How do you know what someone will do when the push comes to shove?",
    "What's the right thing to do?",
    "What's the silver bullet?",
    "How do you know?",
    "Why not?",
    "Who do you look up to who is secretly miserable?",
    "Why is democracy the best form of government?",
    "Why did Islam Karimov establish such a strict authoritarian regime after independence, when many Uzbeks hoped for liberalization?",
    "Which of your strongest beliefs are formed on second-hand information vs. first-hand experience?",
    "What haven't I experienced firsthand that leaves me naive to how something works? As Jeff Immelt said, \"Every job looks easy when you're not the one doing it.\"",
    "Why has Uzbekistan been slower to open politically and economically compared to neighbors like Kazakhstan, despite having rich resources and a strong cultural heritage?",
    "What are you addicted to that doesn't look like an addiction?",
    "What's the best way to say 'no' without guilt?",
    "If your industry disappeared tomorrow, what would you proudly say you contributed?",
    "Why is the market capitalization of Facebook, founded 15 months prior to YC by a 19 year old, larger than that of all YC companies combined?",
    "Is the fear of being wrong so strong that most people prefer consensus over truth?",
    "What question do you _not_ want someone to ask you?",
    "What's the most important thing you've changed your mind about in the last week/month/year/decade?",
    "What's the most you'd pay *not* to do your job for a year?",
    "Why do most people fail to leverage the internet's infinite scalability, even when the tools are (almost) free? Is that a zero-sum game?",
    "What do you desperately want to be true, so much that you think it's true when it's clearly not?",
    "How do you make decisions today that your future self won't regret, given that you'll be a different person?",
    "Is the goal of reading to collect ideas or to dissolve your existing ones?",
    "How would your views change if you had 10,000 years of good, apples-to-apples data on things you only have recent history to study?",
    "How do you know if you're being patient (a skill) or stubborn (a flaw)? They're hard to tell apart without hindsight.",
    "What's the most embarrassing (but true) opinion you hold?",
    "Why do we call it 'the universe' instead of 'God' when it does all the same things (creates, destroys, governs)?",
    "Can true wealth exist without some form of exploitation, or is all capital accumulation inherently extractive?",
    "Why do we accept 'science' as dogma rather than as a process of discovering new knowledge?",
    "Why do most breakthroughs come from outsiders (e.g., Wright brothers, Katalin Karikó)?",
    "Is expertise overrated? Does it create blind spots?",
    "Could the best way to find secrets be to avoid formal training in a field?",
    "Why do we trust 'peer-reviewed' consensus when most breakthroughs come from outsiders?",
    "Whose advice has been so correct in the past that you now just go and act on it?",
    "Which parts of your life feel like theater?",
    "If money were irrelevant, would you still be doing what you're doing?",
    "What's an 'unfair advantage' you have that you're not using?",
    "Do you have any opinions that you would be reluctant to express in front of a group of your peers? What are they? Why reluctant?",
    "Which of your current views would change if your incentives were different?",
    "How to go to the center of the universe?",
    "What part of your identity is holding you back?",
    "Is unconditional love possible, or is all love transactional at some level? How do you maintain independence while deeply loving someone?",
    "What's the simplest way to get what you want?",
    "When was the last time you did something you've never done before?",
    "What important truths do very few people agree with you on?",
    "Why do governments regulate innovation when history shows it's the only way society improves?",
    "What would future-you regret not doing today?",
    "Is your life aligned with your values, or are you living someone else's idea of success?",
    "What if the thing you're most proud of is also your biggest limitation?",
    "What are the scientific rules for life?",
    "How did the Romanovs manage to rule Russia for 300 years?",
    "What events very nearly happened that would have fundamentally changed the world as we know it?",
    "What would you die for?",
    "How much have things outside of your control contributed to things you take credit for?",
    "Can a company survive long-term if its secret gets out?",
    "Why did the Japanese keep debating whether to surrender even after two nuclear bombings?",
    "What would you do in utopia?",
    "What's a norm today that will seem barbaric in 50 years?",
    "Why do you live where you live?",
    "What's something you believe that almost nobody agrees with you on?",
    "What big, bold challenge excites me enough to dedicate years to solving it?",
    "Is it possible to wield power without corruption, or is power itself the corrupting force?",
    "When was the last time you took 3 months completely off?",
    "What's the best book you've read that changed your perspective?",
    "Why did the anarchists murder the single most progressive Russian emperor?"
  ]

  return (
    <>
      <Navigation />
      <main className="min-h-screen pt-32">
        <div className="max-w-4xl mx-auto px-8">
          <h1 className="text-5xl font-bold text-gray-900 dark:text-gray-100 mb-4 text-center">Questions</h1>
          <p className="text-xl text-gray-600 dark:text-gray-400 mb-16 text-center max-w-2xl mx-auto">
            Questions I'm asking myself. Some have answers, some don't. The important ones rarely do.
          </p>

          {/* Questions List */}
          <div className="space-y-6 max-w-2xl mx-auto">
            {questions.map((question, index) => (
              <div 
                key={index}
                className="group cursor-pointer"
              >
                <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors leading-relaxed">
                  {question.split(/(\*[^*]+\*|_[^_]+_)/).map((part, partIndex) => {
                    if (part.startsWith('*') && part.endsWith('*')) {
                      return <em key={partIndex} className="italic">{part.slice(1, -1)}</em>
                    } else if (part.startsWith('_') && part.endsWith('_')) {
                      return <em key={partIndex} className="italic">{part.slice(1, -1)}</em>
                    }
                    return part
                  })}
                </h3>
              </div>
            ))}
          </div>

          {/* Footer Note */}
          <div className="mt-16 text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              These questions evolve over time. Some get answered, some get replaced, some stay with me forever.
            </p>
          </div>
        </div>
      </main>
    </>
  )
}
